Update deploy-to-minikube-github-actions.yaml

diff --git a/.github/workflows/deploy-to-minikube-github-actions.yaml b/.github/workflows/deploy-to-minikube-github-actions.yaml
--- a/.github/workflows/deploy-to-minikube-github-actions.yaml
+++ b/.github/workflows/deploy-to-minikube-github-actions.yaml
@@ -1,28 +1,33 @@
 name: Deploy to Minikube using GitHub Actions
 
-on: [push]
-  
+on:
+  push:
+    branches:
+      - main
+
 jobs:
   job1:
     runs-on: ubuntu-latest
     name: build Node.js Docker Image and deploy to minikube
     steps:
-    - uses: actions/checkout@v2
-    - name: Start minikube
-      uses: medyagh/setup-minikube@master
-    - name: Try the cluster !
-      run: kubectl get pods -A
-    - name: Build image
-      run: |
-          export SHELL=/bin/bash
-          eval $(minikube -p minikube docker-env)
-          docker build -f ./Dockerfile -t devopshint/node-app:latest .
-          echo -n "verifying images:"
-          docker images         
-    - name: Deploy to minikube
-      run:
-        kubectl apply -f k8s-node-app.yaml
-    - name: Test service URLs
-      run: |
-          minikube service list
-          minikube service nodejs-app --url
+      - uses: actions/checkout@v4
+      - name: Start minikube
+        uses: medyagh/setup-minikube@latest
+      - name: Try the cluster !
+        run: minikube kubectl -- get po -A
+      - name: Build image
+        run: |
+            set -e # Exit immediately if a command exits with a non-zero status
+            export SHELL=/bin/bash
+            eval $(minikube -p minikube docker-env)
+            docker build -f ./Dockerfile -t devopshint/node-app:latest .
+            echo -n "verifying images:"
+            docker images         
+      - name: Deploy to minikube
+        run: |
+          kubectl apply -f k8s-node-app.yaml
+          kubectl wait --for=condition=ready pod -l app=nodejs-app
+      - name: Test service URLs
+        run: |
+            minikube service list
+            minikube service nodejs-app-svc --url
